config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/game", to: "games#new"
  get "/score", to: "games#score"
  post "/score", to: "games#score"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'httparty'

class GamesController < ApplicationController
  def new
    @letters = Array.new(10) { ('A'..'Z').to_a.sample }
    session[:letters] = @letters
  end

  def score
    @word = params[:word]
    @letters = session[:letters] || []
    @result = check_word(@word, @letters)
  end

  private

 def check_word(word, letters)
    word_array = word.upcase.split("")

    # Check if the word can be formed from the given letters
    word_array.each do |letter|
        if word_array.count(letter) > letters.count(letter)
            return "Sorry but '#{word}' can't be built out of #{letters}"
        end
    end

    url = "https://wagon-dictionary.herokuapp.com/#{word}"
    response = HTTParty.get(url)
    json = JSON.parse(response.body)
    if json["found"] == false
      return "Sorry but '#{word}' does not seem to be a valid English word..."
    else
      return "Congratulations! '#{word}' is a valid English word!"
    end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<div class="container mt-5">
  <div class="d-flex flex-column align-items-center border border-primary p-5 justify-content-center">
    <h1>New Game</h1>
    <br>
    <h3><%= @letters.join(' - ') %></h3>
    <div class="m-3 d-flex flex-column justify-content-center ">
      <form action="/score" class="text-center">
        <input type="text" name="word" placeholder="Your word">
        <div class="d-flex justify-content-center align-items-center mt-3">
          <button type="submit" class="btn btn-primary">Go</button>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/games/score.html.erb
<div class="container mt-5">
  <div class="d-flex flex-column align-items-center border border-primary p-5 justify-content-center">
    <h1>Result</h1>
    <br>
    <h5><%= @result%></h5>
    <%= link_to "new game?", game_path, class:"btn btn-primary"%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>